// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oncfqzeykwcniuuknlrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uY2ZxemV5a3djbml1dWtubHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MTk1NDIsImV4cCI6MjA1NTQ5NTU0Mn0.QMY0Z-8ICcBRvE9mTJ1Qb0ekbSQOwcU7g8z_XToGNHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
